<?php declare(strict_types=1);

namespace Reconmap\Models;

/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
class CustomField {

	public ?int $id;
	public ?string $parent_type;
	public ?string $name;
	public ?string $label;
	public ?string $kind;
	public ?string $config;
}
