<?php declare(strict_types=1);

namespace Reconmap\Models;

/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
class Notification {

	public int $toUserId;
	public ?string $title;
	public string $content;
}
