<?php declare(strict_types=1);

namespace Reconmap\Models;

/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
class Organisation {

	public ?int $id = null;
	public ?string $insert_ts;
	public ?string $update_ts;
	public string $name = '';
	public ?string $url = null;
	public ?int $contact_id = null;
	public ?string $contact_name = null;
	public ?string $contact_email = null;
	public ?string $contact_phone = null;
	public ?int $logo_attachment_id = null;
	public ?int $small_logo_attachment_id = null;
}
