<?php declare(strict_types=1);

namespace Reconmap\Models;

/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
class Project {

	public ?int $id = null;
	public ?int $creator_uid;
	public ?int $client_id;
	public ?string $name;
	public ?string $description;
	public ?string $visibility = 'public';
	public bool $is_template = false;
	public ?int $category_id;
	public ?string $engagement_start_date;
	public ?string $engagement_end_date;
	public ?string $external_id;
	public ?string $vulnerability_metrics;
}
