services:
  api:
    container_name: rmap-api
    image: ghcr.io/reconmap/rest-api:latest
    build:
      context: ./
      dockerfile: docker/api/development.Dockerfile
    volumes:
      - "./config.json:/var/www/webapp/config.json"
      - "./logs:/var/www/webapp/logs"
      - "./data:/var/www/webapp/data"
      - "./composer.json:/var/www/webapp/composer.json"
      - "./composer.lock:/var/www/webapp/composer.lock"
      - "./vendor:/var/www/webapp/vendor"
      - "./public:/var/www/webapp/public"
      - "./docs/openapi.yaml:/var/www/webapp/public/docs/openapi.yaml"
      - "./docs/schemas/:/var/www/webapp/public/docs/schemas/"
      - "./src:/var/www/webapp/src"
      - "./resources:/var/www/webapp/resources"
      - "./tests:/var/www/webapp/tests"
      - "./phpunit.xml.dist:/var/www/webapp/phpunit.xml.dist"
      - "./run-tests.sh:/var/www/webapp/run-tests.sh"
      - "./database:/var/www/webapp/database"
    ports:
      - "5510:5510"
    extra_hosts:
      host.docker.internal: host-gateway
    environment:
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=DOCKER_SERVER}
      XDEBUG_MODE: ${XDEBUG_MODE:-debug}
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      XDEBUG_TRIGGER: "yes"
