TRUNCATE TABLE user;
INSERT INTO user (id, full_name, username, password, email, role)
VALUES (1, 'Administrator', 'admin', '$2y$10$CrblfxMv8e1ynu9RG54Cau.8dcmz.SpT7nNERclfGMZSbYHoQQuuq', 'admin@localhost',
        'administrator');

TRUNCATE TABLE audit_log;
INSERT INTO audit_log (user_id, client_ip, action)
VALUES (0, INET_ATON('127.0.0.1'), 'Initialised system');

TRUNCATE TABLE vulnerability_category;
INSERT INTO vulnerability_category (id, parent_id, name, description)
VALUES (1,NULL,'Access Controls', 'Related to authorization of users, and assessment of rights.'),
       (2,NULL,'Auditing and Logging', 'Related to auditing of actions, or logging of problems.'),
       (3,NULL,'Authentication', 'Related to the identification of users.'),
       (4,NULL,'Configuration', 'Related to security configurations of servers, devices, or software.'),
       (5,NULL,'Cryptography', 'Related to mathematical protections for data.'),
       (6,NULL,'Data Exposure', 'Related to unintended exposure of sensitive information.'),
       (7,NULL,'Data Validation', 'Related to improper reliance on the structure or values of data.'),
       (8,NULL,'Denial of Service', 'Related to causing system failure.'),
       (9,NULL,'Error Reporting', 'Related to the reporting of error conditions in a secure fashion.'),
       (10,NULL,'Patching', 'Related to keeping software up to date.'),
       (11,NULL,'Session Management', 'Related to the identification of authenticated users.'),
       (12,NULL,'Timing', 'Related to race conditions, locking, or order of operations.'),
       (13,NULL,'OWASP WSTG','Categories based on OWASP Web Security Testing Guide'),
       (22,13,'4.01 - WSTG-INFO-01 (Conduct Search Engine Discovery and Reconnaissance for Information Leakage)',''),
       (23,13,'4.01 - WSTG-INFO-02 (Fingerprint Web Server)',''),
       (24,13,'4.01 - WSTG-INFO-03 (Review Webserver Metafiles for Information Leakage)',''),
       (25,13,'4.01 - WSTG-INFO-04 (Enumerate Applications on Webserver)',''),
       (26,13,'4.01 - WSTG-INFO-05 (Review Webpage Comments and Metadata for Information Leakage)',''),
       (27,13,'4.01 - WSTG-INFO-06 (Identify application entry points)',''),
       (28,13,'4.01 - WSTG-INFO-07 (Map execution paths through application)',''),
       (29,13,'4.01 - WSTG-INFO-08 (Fingerprint Web Application Framework)',''),
       (30,13,'4.01 - WSTG-INFO-09 (Fingerprint Web Application)',''),
       (31,13,'4.01 - WSTG-INFO-10 (Map Application Architecture )',''),
       (32,13,'4.02 - WSTG-CONF-01 (Test Network/Infrastructure Configuration)',''),
       (33,13,'4.02 - WSTG-CONF-02 (Test Application Platform Configuration)',''),
       (34,13,'4.02 - WSTG-CONF-03 (Test File Extensions Handling for Sensitive Information)',''),
       (35,13,'4.02 - WSTG-CONF-04 (Test Backup and Unreferenced Files for Sensitive Information)',''),
       (36,13,'4.02 - WSTG-CONF-05 (Enumerate Infrastructure and Application Admin Interfaces)',''),
       (37,13,'4.02 - WSTG-CONF-06 (Test HTTP Methods)',''),
       (38,13,'4.02 - WSTG-CONF-07 (Test HTTP Strict Transport Security)',''),
       (39,13,'4.02 - WSTG-CONF-08 (Test RIA cross domain policy)',''),
       (40,13,'4.02 - WSTG-CONF-09 (Test File Permission)',''),
       (41,13,'4.02 - WSTG-CONF-10 (Test for Subdomain Takeover)',''),
       (42,13,'4.02 - WSTG-CONF-11 (Test Cloud Storage)',''),
       (43,13,'4.03 - WSTG-IDNT-01 (Test Role Definitions)',''),
       (44,13,'4.03 - WSTG-IDNT-02 (Test User Registration Process)',''),
       (45,13,'4.03 - WSTG-IDNT-03 (Test Account Provisioning Process)',''),
       (46,13,'4.03 - WSTG-IDNT-04 (Testing for Account Enumeration and Guessable User Account)',''),
       (47,13,'4.03 - WSTG-IDNT-05 (Testing for Weak or unenforced username policy)',''),
       (48,13,'4.04 - WSTG-ATHN-01 (Testing for Credentials Transported over an Encrypted Channel)',''),
       (49,13,'4.04 - WSTG-ATHN-02 (Testing for default credentials)',''),
       (50,13,'4.04 - WSTG-ATHN-03 (Testing for Weak lock out mechanism)',''),
       (51,13,'4.04 - WSTG-ATHN-04 (Testing for bypassing authentication schema)',''),
       (52,13,'4.04 - WSTG-ATHN-05 (Testing for Vulnerable remember password)',''),
       (53,13,'4.04 - WSTG-ATHN-06 (Testing for Browser cache weakness)',''),
       (54,13,'4.04 - WSTG-ATHN-07 (Testing for Weak password policy)',''),
       (55,13,'4.04 - WSTG-ATHN-08 (Testing for Weak security question/answer)',''),
       (56,13,'4.04 - WSTG-ATHN-09 (Testing for weak password change or reset functionalities)',''),
       (57,13,'4.04 - WSTG-ATHN-10 (Testing for Weaker authentication in alternative channel)',''),
       (58,13,'4.05 - WSTG-ATHZ-01 (Testing Directory traversal/file include)',''),
       (59,13,'4.05 - WSTG-ATHZ-02 (Testing for bypassing authorization schema)',''),
       (60,13,'4.05 - WSTG-ATHZ-03 (Testing for Privilege Escalation)',''),
       (61,13,'4.05 - WSTG-ATHZ-04 (Testing for Insecure Direct Object References)',''),
       (62,13,'4.06 - WSTG-SESS-01 (Testing for Bypassing Session Management Schema)',''),
       (63,13,'4.06 - WSTG-SESS-02 (Testing for Cookies attributes)',''),
       (64,13,'4.06 - WSTG-SESS-03 (Testing for Session Fixation)',''),
       (65,13,'4.06 - WSTG-SESS-04 (Testing for Exposed Session Variables)',''),
       (66,13,'4.06 - WSTG-SESS-05 (Testing for Cross Site Request Forgery)',''),
       (67,13,'4.06 - WSTG-SESS-06 (Testing for logout functionality)',''),
       (68,13,'4.06 - WSTG-SESS-07 (Testing Session Timeout)',''),
       (69,13,'4.06 - WSTG-SESS-08 (Testing for Session puzzling)',''),
       (70,13,'4.07 - WSTG-INPV-01 (Testing for Reflected Cross Site Scripting)',''),
       (71,13,'4.07 - WSTG-INPV-02 (Testing for Stored Cross Site Scripting)',''),
       (72,13,'4.07 - WSTG-INPV-03 (Testing for HTTP Verb Tampering)',''),
       (73,13,'4.07 - WSTG-INPV-04 (Testing for HTTP Parameter pollution)',''),
       (74,13,'4.07 - WSTG-INPV-05 (Testing for SQL Injection)',''),
       (75,13,'4.07 - WSTG-INPV-06 (Testing for LDAP Injection)',''),
       (76,13,'4.07 - WSTG-INPV-07 (Testing for XML Injection)',''),
       (77,13,'4.07 - WSTG-INPV-08 (Testing for SSI Injection)',''),
       (78,13,'4.07 - WSTG-INPV-09 (Testing for XPath Injection)',''),
       (79,13,'4.07 - WSTG-INPV-10 (Testing for IMAP SMTP Injection)',''),
       (80,13,'4.07 - WSTG-INPV-11 (Testing for Code Injection)',''),
       (81,13,'4.07 - WSTG-INPV-12 (Testing for Command Injection)',''),
       (82,13,'4.07 - WSTG-INPV-13 (Testing for Buffer overflow)',''),
       (83,13,'4.07 - WSTG-INPV-14 (Testing for incubated vulnerabilities)',''),
       (84,13,'4.07 - WSTG-INPV-15 (Testing for HTTP Splitting/Smuggling)',''),
       (85,13,'4.07 - WSTG-INPV-16 (Testing for HTTP Incoming Requests)',''),
       (86,13,'4.07 - WSTG-INPV-17 (Testing for Host Header Injection)',''),
       (87,13,'4.07 - WSTG-INPV-18 (Testing for Server Side Template Injection)',''),
       (88,13,'4.08 - WSTG-ERRH-01 (Testing for Improper Error Handling)',''),
       (89,13,'4.08 - WSTG-ERRH-02 (Testing for Stack Traces)',''),
       (90,13,'4.09 - WSTG-CRYP-01 (Testing for Weak SSL/TSL Ciphers, Insufficient Transport Layer Protection)',''),
       (91,13,'4.09 - WSTG-CRYP-02 (Testing for Padding Oracle)',''),
       (92,13,'4.09 - WSTG-CRYP-03 (Testing for Sensitive information sent via unencrypted channels)',''),
       (93,13,'4.09 - WSTG-CRYP-04 (Testing for Weak Encryption)',''),
       (95,13,'4.10 - WSTG-BUSL-02 (Test Ability to Forge Requests)',''),
       (94,13,'4.10 - WSTG-BUSL-01 (Test Business Logic Data Validation)',''),
       (96,13,'4.10 - WSTG-BUSL-03 (Test Integrity Checks)',''),
       (97,13,'4.10 - WSTG-BUSL-04 (Test for Process Timing)',''),
       (98,13,'4.10 - WSTG-BUSL-05 (Test Number of Times a Function Can be Used Limits)',''),
       (99,13,'4.10 - WSTG-BUSL-06 (Testing for the Circumvention of Work Flows)',''),
       (100,13,'4.10 - WSTG-BUSL-07 (Test Defenses Against Application Mis-use)',''),
       (101,13,'4.10 - WSTG-BUSL-08 (Test Upload of Unexpected File Types)',''),
       (102,13,'4.10 - WSTG-BUSL-09 (Test Upload of Malicious Files)',''),
       (103,13,'4.11 - WSTG-CLNT-01 (Testing for DOM based Cross Site Scripting)',''),
       (104,13,'4.11 - WSTG-CLNT-02 (Testing for JavaScript Execution)',''),
       (105,13,'4.11 - WSTG-CLNT-03 (Testing for HTML Injection)',''),
       (106,13,'4.11 - WSTG-CLNT-04 (Testing for Client Side URL Redirect)',''),
       (107,13,'4.11 - WSTG-CLNT-05 (Testing for CSS Injection)',''),
       (108,13,'4.11 - WSTG-CLNT-06 (Testing for Client Side Resource Manipulation)',''),
       (109,13,'4.11 - WSTG-CLNT-07 (Testing Cross Origin Resource Sharing)',''),
       (110,13,'4.11 - WSTG-CLNT-08 (Testing for Cross Site Flashing)',''),
       (111,13,'4.11 - WSTG-CLNT-09 (Testing for Clickjacking)',''),
       (112,13,'4.11 - WSTG-CLNT-10 (Testing WebSockets)',''),
       (113,13,'4.11 - WSTG-CLNT-11 (Testing Web Messaging)',''),
       (114,13,'4.11 - WSTG-CLNT-12 (Testing Browser Storage)',''),
       (115,13,'4.11 - WSTG-CLNT-13 (Testing for Cross Site Script Inclusion)','');

TRUNCATE TABLE organisation;
INSERT INTO organisation (name, url, contact_email)
VALUES ('Reconmap default org', 'https://reconmap.org', 'no-reply@reconmap.org');

INSERT INTO report (project_id, generated_by_uid, is_template, version_name, version_description)
VALUES (0, 0, 1, 'Default', 'Default report template');

INSERT INTO attachment (parent_type, parent_id, submitter_uid, client_file_name, file_name, file_size, file_mimetype,
                        file_hash)
VALUES ('report', LAST_INSERT_ID(), 0, 'default-report-template.docx', 'default-report-template.docx', 0,
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document', '');
