
DROP TABLE IF EXISTS user;
CREATE TABLE user (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    insert_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_ts TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    name VARCHAR(80) NOT NULL COMMENT 'Username, not full name',
    password VARCHAR(80) NOT NULL,
    email VARCHAR(200) NOT NULL,
    role ENUM('creator', 'writer', 'reader'),
    
        PRIMARY KEY(id),
        UNIQUE KEY(name)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS audit_log;
CREATE TABLE audit_log (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    insert_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id INT UNSIGNED NOT NULL REFERENCES user,
    client_ip INT UNSIGNED NOT NULL COMMENT 'IPv4 IP',
    action VARCHAR(200) NOT NULL,
    
        PRIMARY KEY(id)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS project;
CREATE TABLE project (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    insert_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_ts TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    is_template BOOLEAN NOT NULL DEFAULT FALSE,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(2000) NULL,

        PRIMARY KEY(id),
        UNIQUE KEY(name)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS target;
CREATE TABLE target (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    project_id INT UNSIGNED NOT NULL REFERENCES project,
    insert_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_ts TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    name VARCHAR(200) NOT NULL,
    kind ENUM('host', 'webapp', 'binary'),

        PRIMARY KEY(id),
        UNIQUE KEY(name)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS vulnerability;
CREATE TABLE vulnerability (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    project_id INT UNSIGNED NOT NULL REFERENCES project,
    target_id INT UNSIGNED NOT NULL REFERENCES target,
    reported_by_uid INT UNSIGNED NOT NULL REFERENCES user,
    insert_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_ts TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    summary VARCHAR(200) NOT NULL,
    description VARCHAR(2000) NULL,
    risk ENUM('low', 'medium', 'high') NOT NULL,

        PRIMARY KEY(id)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS task;
CREATE TABLE task (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    project_id INT UNSIGNED NOT NULL REFERENCES project,
    insert_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_ts TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(2000) NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,

        PRIMARY KEY(id),
        UNIQUE KEY(name)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS task_result;
CREATE TABLE task_result (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    task_id INT UNSIGNED NOT NULL REFERENCES task,
    submitted_by_uid INT UNSIGNED NOT NULL REFERENCES user,
    insert_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    output VARCHAR(10000) NOT NULL,

        PRIMARY KEY(id)
) ENGINE=InnoDB;
