
CREATE TABLE project (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(2000) NULL,
    insert_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_ts TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,

        PRIMARY KEY(id),
        UNIQUE KEY(name)
);
