<?php declare(strict_types=1);

namespace Reconmap\Models;

/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
class CommandUsage {

	public ?int $id;
	public ?int $command_id;
	public ?int $creator_uid;
	public ?string $description;
	public ?string $executable_type = 'custom';
	public ?string $executable_path;
	public ?string $docker_image;
	public ?string $arguments;
	public ?string $output_filename;
	public ?string $output_parser;
}
