<?php declare(strict_types=1);

namespace Reconmap\Models;

/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
class Document {

	public ?int $user_id;
	public string $visibility = 'private';
	public ?int $parent_id;
	public ?string $parent_type;
	public ?string $content;
	public ?string $title;
}
