<?php

declare(strict_types=1);

namespace Reconmap\Models;

/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
class Command
{

	public ?int $id;
	public ?int $createdByUid;
	public ?string $name;
	public ?string $description;
	public ?string $moreInfoUrl;
	public ?string $tags;
}
