<?php

declare(strict_types=1);

namespace Reconmap\Models;

/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
class CommandUsage
{

	public ?int $id;
	public ?int $command_id;
	public ?int $createdByUid;
	public ?string $name;
	public ?string $description;
	public ?string $executable_path;
	public ?string $arguments;
	public string $output_capturing_mode = 'none';
	public ?string $output_filename;
	public ?string $output_parser;
}
