<?php declare(strict_types=1);

namespace Reconmap\Models;

/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
class Command {

	public ?int $id;
	public ?int $creator_uid;
	public ?string $name;
	public ?string $description;
	public ?string $more_info_url;
	public ?string $tags;
}
