<?php

declare(strict_types=1);

namespace Reconmap\Models;

/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
class Contact
{

	public ?int $id = null;
	public ?int $organisation_id = null;
	public string $kind = 'general';
	public ?string $name = null;
	public ?string $email = null;
	public ?string $phone = null;
	public ?string $role = null;
}
