<?php

declare(strict_types=1);

namespace Reconmap\Models;

/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
class Note
{

	public ?int $created_by_uid;
	public string $visibility = 'private';
	public ?int $parent_id;
	public ?string $parent_type;
	public ?string $content;
}
