<?php

declare(strict_types=1);

namespace Reconmap\Models;

/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
class Report
{

	public ?int $id = null;
	public ?int $project_id = null;
	public ?int $created_by_uid = null;
	public ?bool $is_template = false;
	public ?string $created_at = null;
	public ?string $version_name = null;
	public ?string $version_description = null;
}
