<?php declare(strict_types=1);

namespace Reconmap\Models;

/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
class Report {

	public ?int $id = null;
	public ?int $projectId = null;
	public ?int $generatedByUid = null;
	public ?bool $is_template = false;
	public ?string $insertTs = null;
	public ?string $versionName = null;
	public ?string $versionDescription = null;
}
