<?php

declare(strict_types=1);

namespace Reconmap\Models;

/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
class Task
{

	public ?int $id;
	public ?int $project_id;
	public ?int $created_by_uid;
	public ?int $assigned_to_uid;
	public ?string $created_at;
	public ?string $updated_at;
	public string $priority = 'medium';
	public string $summary = '';
	public ?string $description = '';
	public string $status = 'todo';
	public ?int $duration_estimate = null;
	public ?string $due_date = null;
	public ?int $command_id;
	public ?string $command;
	public ?string $command_parser;
}
