<?php declare(strict_types=1);

namespace Reconmap\Models;

/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
class User {

	public ?int $id;
	public ?string $insert_ts;
	public ?string $update_ts;
	public ?string $last_login_ts;
	public ?string $subject_id;
	public ?bool $active = true;
	public bool $mfa_enabled = false;
	public string $first_name;
	public string $last_name;
	public ?string $full_name = '';
	public ?string $short_bio;
	public string $username;
	public string $email;
	public string $timezone;
	public mixed $preferences;
	public ?string $role = null;
}
