<?php

declare(strict_types=1);

namespace Reconmap\Models;

/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
class Vault
{

	public ?int $id = null;
	public ?string $created_at = null;
	public ?string $updated_at = null;
	public ?int $owner_uid = null;
	public ?int $project_id = null;
	public string $type = 'password';
	public ?string $name = null;
	public ?string $value = null;
	public ?string $url = null;
	public ?string $expiration_date = null;
	public ?string $note = null;
}
